version: '3.5'

services:
  python:
    build: .
    command: python bot/client.py
    tty: true
    volumes:
      - ./bot:/app/bot
      - ./vendor:/app/vendor:cached
    ports:
      - "8000:8000"
    environment:
      DISCORD_BOT_TOKEN: /var/run/secrets/discord_bot_token
    secrets:
      - discord_bot_token

secrets:
  discord_bot_token:
    file: ./secrets/discord_bot_token
